name: visual_graphs
description: "A Graph Algorithm visualizer"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  collection: ^1.19.1
  flame: ^1.32.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  icons_launcher: ^3.0.2

flutter:
  uses-material-design: true
